/*
 * Copyright (c) 2009-2015 Samsung Electronics Co., Ltd All Rights Reserved
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

#include <libintl.h>
#include "cst-common-string.h"
#include "cst-common.h"

#undef _
#undef N_
#define _(s)				dgettext(APPNAME, s)
#define dgettext_noop(s)	(s)
#define N_(s)				dgettext_noop(s)

static const char *cst_str[] = {
	N_("IDS_CST_BODY_ALERTS_ON_CALL"),
	N_("IDS_ST_BODY_ON_OFF_BUTTON"),
	N_("IDS_CST_BODY_ALL_INCOMING_CALLS"),
	N_("IDS_CST_BODY_ALL_OUTGOING_CALLS"),
	N_("IDS_CST_BODY_CALL_WAITING"),
	N_("IDS_CST_BODY_BY_NETWORK"),
	N_("IDS_CST_OPT_SHOW"),
	N_("IDS_CST_OPT_HIDE"),
	N_("IDS_CST_BODY_INTL_CALLS_EXCEPT_HOME"),
	N_("IDS_CST_BODY_INTL_CALLS"),
	N_("IDS_CST_MBODY_MY_CALLER_ID"),
	N_("IDS_CST_BODY_ALWAYS_FORWARD"),
	N_("IDS_CST_MBODY_FORWARD_WHEN_BUSY"),
	N_("IDS_COM_BODY_FORWARD_WHEN_UNANSWERED"),
	N_("IDS_CST_MBODY_FORWARD_WHEN_UNREACHABLE"),
	N_("IDS_CST_POP_INCOMING_WHEN_ROAMING"),
	N_("IDS_CST_POP_INCORRECT_OPERATION"),
	N_("IDS_CST_POP_INVALID_PASSWORD"),
	N_("IDS_CST_POP_PASSWORD_BLOCKED"),
	N_("IDS_CST_POP_REJECTED_BY_NETWORK"),
	N_("IDS_CST_POP_SERVICE_UNAVAILABLE"),
	N_("IDS_CST_POP_UNKNOWN_OPERATION"),
	N_("IDS_CST_BUTTON2_CANCEL"),
	N_("IDS_COM_SK_SET"),
	N_("IDS_CST_BODY_ENTER_NUMBER"),
	N_("IDS_MSG_TPOP_INVALID_NUMBER_ENTERED"),
	N_("IDS_CST_BODY_WRONG_AUTO_REJECT_NUMBER"),
	N_("IDS_CST_POP_NUMBER_ALREADY_IN_USE"),
	N_("IDS_CST_HEADER_REJECT_MESSAGE"),
	N_("IDS_CST_POP_ENTER_MESSAGE"),
	N_("IDS_CST_BODY_SOUND"),
	N_("IDS_CST_HEADER_ANSWERING_ENDING_CALLS_ABB"),
	N_("IDS_CST_BODY_CALL_FORWARDING"),
	N_("IDS_CST_BODY_THE_HOME_KEY_ANSWERS_CALLS"),
	N_("IDS_CST_BODY_THE_POWER_KEY_ENDS_CALLS_ABB2"),
	N_("IDS_CST_BODY_VIDEO_CALL_IMAGE"),
	N_("IDS_CST_BODY_SET_DEFAULT_HIDE_ME_IMAGE"),
	N_("IDS_CST_SK_CHANGE_IMAGE"),
	N_("IDS_CST_BODY_MANAGE_CALL_ANSWERING_ENDING_SETTINGS_ABB"),
	N_("IDS_CST_HEADER_FORWARD_TO"),
	N_("IDS_CST_BODY_VOICE_MAIL"),
	N_("IDS_COM_POP_INSERT_SIM_CARD"),
	N_("IDS_COM_POP_DEACTIVATE_FLIGHT_MODE_TO_USE_NETWORK_SERVICES"),
	N_("IDS_CST_NPBODY_NO_MESSAGES"),
	N_("IDS_CST_BODY_AFTER_YOU_CREATE_CALL_REJECT_MESSAGES_THEY_WILL_BE_SHOWN_HERE"),
	N_("IDS_CST_MBODY_NOTIFY_DURING_CALLS"),
	N_("IDS_CST_SBODY_ALLOW_ALARMS_AND_NOTIFICATIONS_TO_SOUND_DURING_CALLS"),
	N_("IDS_CST_SBODY_SET_AN_ALTERNATIVE_IMAGE_OR_VIDEO_TO_BE_DISPLAYED_ON_THE_OTHER_PERSONS_SCREEN_DURING_VIDEO_CALLS"),
	N_("IDS_CST_SBODY_COMPOSE_OR_EDIT_RESPONSE_MESSAGES_TO_SEND_WHEN_REJECTING_INCOMING_CALLS"),
	N_("IDS_CST_SBODY_RECEIVE_CALL_ALERTS_DURING_CALLS_ABB"),
	N_("IDS_CST_BODY_TURN_ON_PROXIMITY_SENSOR_DURING_CALLS"),
	N_("IDS_CST_OPT_REMOVE"),
	N_("IDS_CST_BODY_EDIT"),
	N_("IDS_COM_BODY_MORE"),
	N_("IDS_CST_SK_OK"),
	N_("IDS_CST_SK3_CREATE"),
	N_("IDS_CST_HEADER_DELETE"),
	N_("IDS_CST_BODY_ADD"),
	N_("IDS_COM_BODY_SELECT_ALL"),
	N_("IDS_ST_HEADER_PD_SELECTED"),
	N_("IDS_COM_POP_DEACTIVATED"),
	N_("IDS_COM_POP_LOADING_ING"),
	N_("IDS_CST_POP_DISABLE"),
	N_("IDS_CST_BODY_MAXIMUM_NUMBER_OF_CHARACTERS_HPD_REACHED"),
	N_("IDS_ST_BUTTON_DONE"),
	N_("IDS_CST_BODY_NAME"),
	N_("IDS_CST_BUTTON_ENABLE"),
	N_("IDS_CST_POP_MAX_CONTACT_LISTS_REACHED"),
	N_("IDS_CST_BODY_VOICE_MAIL_NUMBER"),
	N_("IDS_CST_HEADER_VOICE_CALL_FORWARDING"),
	N_("IDS_CST_BODY_VIDEO_CALL_FORWARDING"),
	N_("IDS_CST_MBODY_OUTGOING_CALL_CONDITIONS"),
	N_("IDS_CST_MBODY_OUTGOING_CALL_TYPE"),
	N_("IDS_CST_BODY_INCOMING_CALL_SOUND_DEVICE_ABB"),
	N_("IDS_CST_BODY_REDIAL_LAST_NUMBER"),
	N_("IDS_CST_BODY_2_SECONDS"),
	N_("IDS_CST_BODY_5_SECONDS"),
	N_("IDS_CST_BODY_10_SECONDS"),
	N_("IDS_CST_OPT_EVEN_WHEN_DEVICE_LOCKED_ABB"),
	N_("IDS_CST_BODY_MAKE_CALLS_EVEN_WHEN_DEVICE_LOCKED"),
	N_("IDS_CST_BODY_ONLY_WHEN_DEVICE_UNLOCKED_ABB"),
	N_("IDS_CST_HEADER_HEADSET_SETTINGS_FOR_INCOMING_CALLS"),
	N_("IDS_CST_MBODY_AUTOMATIC_ANSWERING"),
	N_("IDS_CST_MBODY_AUTOMATIC_ANSWERING_TIMER"),
	N_("IDS_CST_BODY_CONNECT_A_HEADSET_TO_ENABLE_AUTOMATIC_ANSWERING"),
	N_("IDS_CST_BODY_ADJUST_AUTOMATIC_ANSWERING_DELAY_FOR_INCOMING_CALLS"),
	N_("IDS_CST_HEADER_BT_HEADSET_SETTINGS_FOR_OUTGOING_CALLS"),
	N_("IDS_CST_BODY_SELECT_DEVICE_FOR_INCOMING_CALL_SOUND_ABB"),
	N_("IDS_CST_OPT_BOOST_LOW_TONES_ABB"),
	N_("IDS_CST_OPT_BOOST_HIGH_TONES_ABB"),
	N_("IDS_CST_MBODY_EYE_CONTACT"),
	N_("IDS_CST_BODY_MODIFY_MY_EYES_TO_SEEM_LIKE_I_AM_LOOKING_AT_CAMERA_DURING_VIDEO_CALLS"),
	N_("IDS_CST_BODY_SUPPRESSES_BACKGROUND_NOISE_FROM_YOUR_SIDE_DURING_CALLS"),
	N_("IDS_CST_BODY_FIND_THE_BEST_EQ_FOR_YOU"),
	N_("IDS_CST_MBODY_OPTIMISED_FOR_LEFT_EAR"),
	N_("IDS_CST_MBODY_OPTIMISED_FOR_RIGHT_EAR"),
	N_("IDS_CST_MBODY_USE_EXTRA_VOL_FOR_CALLS"),
	N_("IDS_CST_BODY_EXTRA_VOLUME_BUTTON_IS_SHOWN_ON_SCREEN_DURING_CALLS"),
	N_("IDS_COM_OPT_CREATE_CONTACT"),
	N_("IDS_CST_BODY_NUMBER"),
	N_("IDS_CST_BODY_WAITING_TIME"),
	N_("IDS_CST_BODY_PD_SECONDS"),
	N_("IDS_CST_MBODY_MY_CALL_SOUND"),
	N_("IDS_CST_MBODY_MY_CALL_SOUND_SETTINGS"),
	N_("IDS_CST_BODY_END_WITH"),
	N_("IDS_ST_POP_ALREADY_IN_USE"),
	N_("IDS_CST_HEADER_CALL_REJECT_MESSAGES_ABB"),
	N_("IDS_CLOG_POP_UNABLE_TO_CHANGE_VOICEMAIL_NUMBER_CONTACT_CARRIER_IF_THIS_PROBLEM_PERSISTS"),
	N_("IDS_COM_POP_REQUESTING"),
	N_("IDS_ST_BODY_SHOW_PASSWORD"),
	N_("IDS_MSG_TPOP_MAXIMUM_NUMBER_OF_DIGITS_HPD_REACHED"),/*ToDo: Move to po file*/
	N_("IDS_ST_BODY_PHONEPROFILES_SILENT"),
	N_("IDS_VCALL_BODY_BT_HEADSET"),
	N_("IDS_CST_MBODY_CALL_ALERTS"),
	N_("Incoming call notifications"),
	N_("Display notification pop-ups for incoming calls when the screen is on"),
	N_("IDS_CST_MBODY_CALL_VIBRATIONS"),
	N_("IDS_CST_MBODY_ANSWER_VIBRATION"),
	N_("IDS_CST_BODY_THE_CALLERS_DEVICE_VIBRATES_WHEN_RECIPIENTS_ANSWER_THE_PHONE"),
	N_("IDS_CST_MBODY_CALL_END_VIBRATION"),
	N_("IDS_CST_BODY_THE_CALLERS_DEVICE_WILL_VIBRATE_WHEN_THE_CALL_ENDS"),
	N_("IDS_CST_BODY_TURN_ON_ALARM_AND_MESSAGE_NOTIFICATIONS_DURING_CALLS"),
	N_("IDS_CST_BODY_USE_CALL_FAIL_OPTIONS"),
	N_("IDS_CST_BODY_USE_ALTERNATIVE_METHODS_TO_REDIAL_FAILED_CALLS"),
	N_("IDS_COM_BODY_UNKNOWN_M_CALL"),
	N_("IDS_CST_BODY_RINGTONES_AND_KEYPAD_TONES_ABB"),
	N_("IDS_ST_BODY_VIBRATIONS"),
	N_("IDS_ST_HEADER_KEYPAD_TONES"),
	N_("IDS_ST_BODY_PLAY_TONES_WHEN_KEYPAD_IS_PRESSED"),
	N_("IDS_CAM_BODY_VOICE_CONTROL_ABB"),
	N_("IDS_CST_HEADER_AUTO_REJECT_MODE"),
	N_("IDS_CST_HEADER_CALL_BLOCK_LIST_ABB"),
	N_("IDS_CST_BODY_NO_NAME"),
	N_("IDS_CST_POP_ALL_INCOMING_CALLS"),
	N_("IDS_CST_BODY_BLOCK_LIST"),
	N_("IDS_CST_HEADER_CALL_BLOCK_LIST_ABB"),
	N_("IDS_CST_BODY_MANAGE_AUTO_REJECT_LIST_ABB"),
	N_("IDS_CST_BODY_AUTO_REDIAL"),
	N_("IDS_CST_BODY_ENABLE_AUTO_REDIAL_IF_CALL_CANNOT_BE_CONNECTED_OR_HAS_BEEN_CUT_OFF"),
	N_("IDS_MEDIABR_BODY_SELECT_ITEMS"),
	N_("IDS_COM_POP_DELETE_Q"),
	N_("IDS_CST_HEADER_CALL_SETTINGS"),
 	N_("IDS_MSG_ACBUTTON_CANCEL_ABB"),
	N_("IDS_MSG_ACBUTTON_DELETE_ABB"),
	N_("IDS_MSG_ACBUTTON_DONE_ABB"),
	N_("IDS_ST_BODY_NOT_SET"),
	N_("IDS_COM_BODY_NO_CHANGES_WERE_MADE"),
	N_("IDS_CST_HEADER_ANSWER_CALLS_BY"),
	N_("IDS_CST_MBODY_PRESSING_THE_HOME_KEY"),
	N_("IDS_CST_HEADER_END_CALLS_BY"),
	N_("IDS_CST_MBODY_PRESSING_THE_POWER_KEY"),
};

static const char *sys_str[] = {
	"",
	"IDS_COM_BODY_ON",
	"IDS_COM_BODY_OFF",
	"IDS_COM_BODY_VOICE_CALL",
	"IDS_COM_BODY_VIDEO_CALL",
	"IDS_COM_BODY_UNKNOWN",
	"IDS_COM_BODY_SELECT_ALL",
	"IDS_COM_BODY_ENTER_PASSWORD",
	"IDS_COM_BODY_PASSWORD",
	"IDS_COM_SK_SAVE",
	"IDS_COM_POP_DELETED",
	"IDS_COM_BODY_APPLICATION_NOT_INSTALLED",
	"IDS_COM_SK_OK",
	"IDS_COM_BODY_FORWARDING",
	"END_OF_TABLE"
};

int _cst_text_id_is_common(const char *text)
{
	int i = 0;
	for (; strcmp(sys_str[i], "END_OF_TABLE") != 0; i++) {
		if (strcmp(text, sys_str[i]) == 0) {
			DBG("text = sys_str[%d] = %s", i, sys_str[i]);
			return EINA_TRUE;
		}
	}
	return EINA_FALSE;
}

const char *_cst_get_text_id(int str_id)
{
	const char **table;

	table = cst_str;
	if (str_id < CST_SYS_STRING) {
		return table[str_id];
	} else {
		return sys_str[str_id - CST_SYS_STRING];
	}
}

const char *_cst_get_text(int str_id)
{
	const char **table;

	table = cst_str;
	if (str_id < CST_SYS_STRING) {
		return dgettext(APPNAME, table[str_id]);
	} else {
		return S_(sys_str[str_id - CST_SYS_STRING]);
	}
}

char *_cst_gettext(const char *s)
{
	if (s == NULL) {
		return "NULL";
	}

	char *p = dgettext(APPNAME, s);

	if (!g_strcmp0(s, p)) {	/* not found */
		/* find in system pkg */
		p = S_(s);
	}
	return p;
}


